### ISSUE TITLE
[ProjectSearch] tracking issue

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1108]
We'd like to re-add the ability to search across the project.

Links 
* Here's the search [invision](https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554_Debugger)
* Here's a link to [chrome's rdp method](https://chromium.googlesource.com/v8/v8/+/master/src/inspector/js_protocol.json#580)

Steps:
- [x] add a UI for showing project search #3090
- [x] Add a component for toggling project search between text and files #3091
- [x] add a text search function 
- [x] Add a redux action for loading source texts #3331
- [x] Move search functionality to redux #3342
- [x] Refactor Project Search to support text search
- [x] Make source search stream #3270
- [x] Create a "search" tab #3279
- [x] Cleanup the css and styles for dark theme #3326
- [x] Auto focus on the first result in the list
- [x] Highlight line where the text match was found when source file is opened #3467
- [x] Add keyboard actions for accessibility #3501
- [x] should scroll to keep items in focus
- [x] File path does not appear in nightly #3782
- [ ] Improve Text Search -> Source Transition #3787
- [ ] Flow type the UI - I started [here], but struggled with ManagedTree.

[here]: https://github.com/jasonLaster/debugger.html/tree/ts-filter-paths

**Comment by clarkbw** [comment]
Pulling this image out so you don't have to jump to the doc.

<img width="883" alt="screen shot 2017-03-12 at 12 03 40 pm" src="https://cloud.githubusercontent.com/assets/2134/23834938/f5d51258-071b-11e7-8dca-3017db057b9a.png">

**Comment by wldcordeiro** [comment]
I'd love to get hacking on this. What/where would I need to work to do these parts?

> add a debugger server endpoint
> add debugger client + command methods

**Comment by jasonLaster** [comment]
I'll break it down soon :)

It's on the q2 roadmap!

**Comment by clarkbw** [comment]
@wanderview really wants this 😄

**Comment by jasonLaster** [comment]
I started hacking on this earlier today and made some progress

Here's the [gist]. I'll post a couple PRs based on the work so that it doesn't go stale soon

- [ ] add a source search function
- [ ] Refactor Project Search to support text search
- [ ] Add a component for toggling project search between text and files
- [ ] Add a redux action for loading source texts

I started one and two and punted on three and four naturally :)


<img src='https://shipusercontent.com/9cfb2581ab2935cc987a1f1808553e2b/Screen%20Shot%202017-06-03%20at%205.02.34%20PM.png' title='Screen Shot 2017-06-03 at 5.02.34 PM.png' width=862>

**Comment by jasonLaster** [comment]
I updated the issue description to have a good checklist

**Comment by jasonLaster** [comment]
- [ ] the results should scroll
- [ ] the selection highlight is too strong in dark theme
- [ ] we should exclude watch expressions (sources should have a URL)

**Comment by jasonLaster** [comment]
Here is a patch for styling project search:
https://gist.github.com/jasonLaster/b02fa35094cf5ef3d5055d329408aefc

**Comment by bughit** [comment]
which firefox version is this planned for?

**Comment by jasonLaster** [comment]
It's turned on nightly today :)

**Comment by jasonLaster** [comment]
going to close this as we have done the big items!
