### ISSUE TITLE
Move source maps to the toolbox

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#1220]
The toolbox needs to actually own sourcemaps so that other tools can access them. This is unfortunately going to make things more complicated, but it's necessary. The most complicated part for us is that sourcemaps will have to live in mozilla-central and we'll have to treat it like a devtools library that we copy over and use locally.

When the toolbox is split off from this project, sourcemaps will likely go with it, so we have a shared "mock" toolbox that also provides sourcemaps. That way when the console also uses the fake toolbox for local development, sourcemaps just work there too.

The first step is to move the `utils/source-map-*` files over to m-c and remove anything specific to our workflow, like flow types. The next step is to make the toolbox in `toolbox.js` create a reference to the sourcemap worker. I've done most of this work already.

The next step, which is the hardest and I'm still thinking through, is figure out a way to change it so that sourcemaps are loaded "lazily". This is needed because we can't fetch all of the sources *and* load all of their sourcemaps eagerly whenever the devtools is open. It's just too slow, and most users don't even touch the debugger. When the toolbox gets a request for a location to be sourcemapped, it needs to somehow load that source and then load & parse its sourcemap. Of course, it'll be cached locally, so subsequent requests will be fast not need to do any extra work.

This shouldn't impact this project too much once I figure out the toolbox integration. Most of my time will be spent on mozilla-central making all this work, and figure out how to lazily load sources.

**Comment by jasonLaster** [comment]
I'm closing this as it's no longer actionable. We should try an ping james and get some of his initial work here.

**Comment by clarkbw** [comment]
@jlongster do you have a branch you can share?

**Comment by jlongster** [comment]
I do not, I've already deleted my mozilla-central repo. All I had done was investigate different ways to do the lazy loading of sources by hacking around in in the sources backend. Basically you need to move the store for sources and sourcemaps up to the toolbox since all tools need to work with them. You might be able to load all the sources when the toolbox opens, and then fetch/parse sourcemaps on demand. I'd start by moving the sources up to the toolbox and see if it's fast enough to load all of them when the toolbox opens.

**Comment by clarkbw** [comment]
Thanks!

**Comment by jryans** [comment]
I'll planning to look into this.

**Comment by jryans** [comment]
I'll use this issue to track the various tasks to complete this work:

- [ ] Copy source map utils out from `debugger.html` to a new package in `devtools-core`
- [ ] Update `debugger.html` to use this new package
- [ ] Land new source map package in m-c
- [ ] Update `debugger.html` to receive source map service from toolbox in Firefox

James had mentioned making things lazy as well to improve pref, but I think we can tackle that separately in follow up work.

**Comment by jasonLaster** [comment]
Closing this for now as the debugger work is primarily done. We can track new work in devtools-core

**Comment by jryans** [comment]
Still work to do in m-c, so let's keep this open for now.

**Comment by jryans** [comment]
Okay, all major tasks completed here. The source map service has moved up to the toolbox and the debugger uses when running as a Firefox panel.

Lots of room for performance improvements, expansion to other tools, etc. but we'll leave that for future issues.
