### ISSUE TITLE
yarn run firefox fails

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1341]
This is a tracking issue for problems that come up with `yarn run firefox`. If you see anything, please let us know and we'll try to keep this issue up to date. 

We'll re-open this issue if there's something wrong.

- [x] [does not set debugger server](https://github.com/devtools-html/debugger.html/issues/906)
- [x] [is not starting firefox with --start-debugger-server](https://github.com/devtools-html/debugger.html/issues/887)
- [x] [firefox crashes](https://github.com/devtools-html/debugger.html/issues/725)
- [x] [throwing error on archlinux](https://github.com/devtools-html/debugger.html/issues/842)
- [x] [fedora 24](https://github.com/devtools-html/debugger.html/issues/1422)

**Comment by jasonLaster** [comment]
@andreicristianpetcu mind sharing your issues with fedora 24:  https://github.com/devtools-html/debugger.html/issues/1347#issuecomment-265875731

**Comment by andreicristianpetcu** [comment]
Since this is a tracking bug, I created a separate issue @jasonLaster https://github.com/devtools-html/debugger.html/issues/1422

**Comment by nmicht** [comment]
If Firefox is installed as an Ubuntu snap when run `yarn run firefox` fails with the message `Your Firefox profile cannot be loaded. It may be missing or inaccessible`

Even so, Firefox as snap do have access to profiles when runs like `SNAP_FIREFOX_PATH/firefox-bin -P`
