### ISSUE TITLE
Editor Search Bar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1412]
Lets turn this on!

Requirements:
- [x] cmd+f selected text, then enter, cmd+g, ... #1568
- [x] The new search bar can overlay the old search bar https://github.com/devtools-html/debugger.html/issues/1194

Nice To have:
- [x] Improve selection highlight #1329 
- [ ] add tests (likely unit tests)
- [x] Localize shortcuts #1078 
- [ ] Search Modifiers #1637

**Comment by wldcordeiro** [comment]
I'm adding some features to the list. Don't know if we want them in nice to have or requirements @jasonLaster

**Comment by jasonLaster** [comment]
Closing this as we're turning this on. We can track these things separately
