### ISSUE TITLE
Vertical Layout

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1488]
Vertical Layout helps users use the debugger in narrow widths

Requirements
- [x] show scope pane on the right #1359 
- [x] show source tree on the left #1358 
- [x] add collapse buttons
- [x] support media widths
- [x] use an accordion for scopes + watch expressions #1677

Nice To Haves
- [x] show the bottom collapse buttons in vertical mode #1537 

### Current UI

![](https://cloud.githubusercontent.com/assets/254562/20759880/510af6f4-b6ec-11e6-8bea-e26872761173.gif)

**Comment by jasonLaster** [comment]
@wldcordeiro and @kdzwinel landed all of the major features. Lets review the UI and file some small polish bugs before we release this.

**Comment by jasonLaster** [comment]
I think this is solid :)
