### ISSUE TITLE
Reveal Source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1495]
Tasks:
- [ ] update copy enhancement #1494
- [x] showing an already revealed source enhancement #1475  
- [x] Fix "revealing and focusing the non selected source"  #1493
