### ISSUE TITLE
Web Test Runner

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1511]
We currently run our integration tests with [Mochitest](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md). It has several benefits:

1. The tests are run end-to-end in Firefox and the devtools panel
2. The tests are driven with redux actions. See this [test](https://github.com/devtools-html/debugger.html/blob/master/src/test/mochitest/browser_dbg-breaking.js#L12-L16) for example.

There are three primary drawbacks with our setup:

1. The tests require a full checkout and build of firefox (this takes time)
2. It's impossible to test chrome or node, which we'd like to support
3. The tests are hard to debug. Using the browser toolbox is cool, but not the most effective tool.

The solution to this is to write a new iframe based test runner.

Tasks:
- [x] setup simple runner https://github.com/devtools-html/debugger.html/pull/1445
- [ ] run our mochitests with the runner #1844
- [ ] update CI to launch chrome and node and run the tests 

How does the runner work:
* it loads the debugger in an iframe 
* it uses mocha as the runner 
* it loads the same redux helpers, it has a couple of global functions that map the mochitest API to mocha / expect.

CC @juliandescottes

**Comment by jasonLaster** [comment]
This is tracked elsewhere
