### ISSUE TITLE
Persist UI across refreshes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1573]
This is a tracking ticket for the several features around persisting UI for debugger or debuggee refreshes:

Features:
- [ ] persist tabs #583
- [ ] persist sidebar collapse
- [x] persist selected source
- [x] persist pause on exceptions
- [x] persist frames, scopes

**Comment by jasonLaster** [comment]
closing as it's a dupe of https://github.com/devtools-html/debugger.html/issues/1586
