### ISSUE TITLE
Hover on a variable

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1574]
Checklist
- [x] Show a popup in CodeMirror #1840
- [x] Add a JS parser in a worker #1841
- [x] Add an `expressionAtLocation` function for getting the expression to eval #1842
- [x] Preview values in the popup #1843

**Comment by SebastianZ** [comment]
For what it's worth, here's a screenshot of how this feature looked in the old UI:

![Variable value infotip](https://cloud.githubusercontent.com/assets/958943/22205208/022b7220-e176-11e6-86f0-6b3c7dbf46a3.png)

And people are already [starting to wonder](http://stackoverflow.com/q/40800183/432681) where this feature is gone.

Because this is a regression in regard of the old UI and a feature that is presumably used quite often, I believe this should get some priority.

Sebastian

**Comment by clarkbw** [comment]
Lets start with an MVP of hover on:

* Variable
* Function

## Variable

Hover over a variable to inspect.  Popup should display:
* ObjectInspector for variable value
* Action to Reveal variable in Scopes
* Action to Add to Watch Expressions

## Function

Hover over a function to inspect.  Popup should display:
* Action to jump to function definition
* Action to find occurrences of function (in current file)

### Chrome

![](https://cloud.githubusercontent.com/assets/95570/18097151/9dbd7b6e-6e91-11e6-9515-2aa261a17772.png)

### DXR

<img width="300" alt="screen shot 2017-01-11 at 3 11 10 pm" src="https://cloud.githubusercontent.com/assets/2134/22262151/9c935090-e224-11e6-91a6-ee98a3fe378b.png">

**Comment by jasonLaster** [comment]
closing this in favor of a more modern tracking issue

**Comment by Nexxado** [comment]
@SebastianZ you're right on that, i'm not using Firefox solely because its missing this critical feature which chrome does flawlessly.

**Comment by jasonLaster** [comment]
@Nexxado what is missing in the current version?

**Comment by Nexxado** [comment]
@jasonLaster sorry,  I should have been more specific.
I'm referring to not being able to see variables value (on hover)  in the debugger

**Comment by jasonLaster** [comment]
@Nexxado that's still pretty vague.

for instance this example should work: https://small-vals.glitch.me/

we intentionally dont show preview popups for out of scope functions.

**Comment by Nexxado** [comment]
@jasonLaster Here (see image) when hovering over the function's arguments I don't see its value.

Could it be related to the fact that the code is minified?
Cause the scopes window to the side shows the minified names of the variables.

Note the Chrome works as expected in this scenario.

### on hover
![image](https://user-images.githubusercontent.com/12609607/32992989-6e1af7aa-cd5a-11e7-996d-68379912c7cf.png)

### scopes menu
![image2](https://user-images.githubusercontent.com/12609607/32993022-d5974104-cd5a-11e7-915d-4abae1254b79.png)

**Comment by jasonLaster** [comment]
Thanks @ryanjduffy @Fischer-L?

**Comment by Fischer-L** [comment]
Tried a similar script but unable to reproduce the issue.
![1574_mimic_but_unable_to_reproduce](https://user-images.githubusercontent.com/5627487/33067387-f5f92de2-cee8-11e7-910c-cddabe79eff1.gif)

Then, tried the minified-like version and able to reproduce.
![1574_mimic_minified_and_able_to_reproduce](https://user-images.githubusercontent.com/5627487/33067424-18497f8c-cee9-11e7-88a0-ec6824fae83a.gif)

This is because the bp now carrys the column criterion, which shouldn't be carried.
![screen shot 2017-11-21 at 6 20 50 pm](https://user-images.githubusercontent.com/5627487/33067533-6bc9993a-cee9-11e7-814f-47da856679ac.png)

This is making #4369 issue happen again.

Not sure my finding has to do with this issue but a bp with the column definitely incorrect.

Don't know which patch makes this bp regression...

Looking into...

**Comment by Fischer-L** [comment]
Seems the bp with column issue lies in the client side

The bp is correctly set to Line:5 without column when setting to client
<img width="474" alt="set_bp_to_client" src="https://user-images.githubusercontent.com/5627487/33229724-54462958-d20f-11e7-9dc1-8e0588b65ac7.png">

While pausing on the bp, the packet from the client says: we are at Line: 5, Column: 4
<img width="940" alt="paused_on_bp" src="https://user-images.githubusercontent.com/5627487/33229761-f2138608-d20f-11e7-90ce-b5f974ca5277.png">

And while creating the frame, we set the location using the frame packet info from the client
https://github.com/devtools-html/debugger.html/blob/5b13fb4770c267ba97a50fa8ca3d9022f0ff8eb1/src/client/firefox/create.js#L28

Last time this part being touched was 2 months ago by PR #3817
But it didn't really change the logic
https://github.com/devtools-html/debugger.html/pull/3817/files#diff-989ecd08734678d3100c0b426a0f33d8

**Comment by jasonLaster** [comment]
How does column 4 cause us to mess up? Also, what example are you using?

I love your writeups Fischer, they're really helpful!

**Comment by Fischer-L** [comment]
@jasonLaster I am using the example above: https://github.com/devtools-html/debugger.html/issues/1574#issuecomment-345984448

When the bp with a column, which shouldn't be there, will see the issue #4369 again, take that for example, paused at the bp (Line: 46, Column: 4), because the location (Line:46, Column: 47 ~ Line: 48, Column:3 ) dose not contain the bp so the entire Line: 46 is ruled as out-of-scope
```js
app.TodoModel.prototype.toggleAll = function (checked) {
  // Note: it's usually better to use immutable data structures since they're
  // easier to reason about and React works very well with them. That's why
  // we use map() and filter() everywhere instead of mutating the array or
  // todo items themselves.
  this.todos = this.todos.map(function (todo) {          // Line: 46
    return Utils.extend({}, todo, {completed: checked}); // Line: 47
  });                                                    // Line: 48

  this.inform();
};
```
