### ISSUE TITLE
Type the Debugger (V1)

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1585]
This issue tracks our work toward adding flow types to the Debugger. We can call this issue *done* when we've added types to the major parts of the debugger and have good patterns in place

- [x] Add types to Editor #1340
- [x] Add types to the client https://github.com/devtools-html/devtools-core/pull/49
- [x] Import types from the client #1598
- [x] Add types to reducers + actions #1179
- [x] Add types to components #1121 
- [x] add types for the source map worker #1026
