### ISSUE TITLE
Persist UI across navigation / refreshes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1586]
We would like UI state to be persisted across navigation / refreshes

**Debugger Refreshes Features**
- [x] you don't see previous tabs when navigating back to a URL #1705
- [x] Persist tabs #1547
- [x] Persist selected source (blocked by #1547)
- [x] Persist start and end panel expand state #1597
- [x] Persist sidebar pane collapse  #1587
- [x] Persist pause on exception state #1534 
- [x] Persist Scope and Frame open state #960
- [x] Persist selected source  #578 

**Debuggee Refreshes Features**
- [x] Persist selected source #578

**Comment by bomsy** [comment]
@jasonLaster Does https://github.com/devtools-html/debugger.html/issues/960 fit in here as well?

**Comment by jasonLaster** [comment]
@bomsy oops, i linked to the wrong issue for #960. #1471 was about auto-expanding :)
