### ISSUE TITLE
Format native objects

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1634]
We have found that there are several native objects that we're not formatting well:

- [x] Fix Location reps properties #1602
- [x] Update non-enumerable styling #1603
- [x] Format mouseEvents #1299
- [x] Show large arrays, objects #2026
- [x] format promises #374
- [x] DOMElements and DOMEvents
- [x] MessageEvents #2849

We should test these: https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by clarkbw** [comment]
both items left are currently in progress

**Comment by clarkbw** [comment]
Looks like we're all done here! 🎉

**Comment by jasonLaster** [comment]
I believe we're done (again)
