### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1635]
It would be great to release a code coverage prototype for user research testing.

- [x] frontend https://github.com/devtools-html/debugger.html/pull/1410
- [ ] land the server prototype https://bugzilla.mozilla.org/show_bug.cgi?id=1322663
- [ ] land the client patch for the protocol https://github.com/devtools-html/devtools-core/pull/20

![](https://camo.githubusercontent.com/fd726484ad73bf685c497ce91fabf78441aacb38/687474703a2f2f672e7265636f726469742e636f2f58307463474f61316d6e2e676966)

**Comment by clarkbw** [comment]
This is our stretch goal.  Putting this off until we get some other items finished.
