### ISSUE TITLE
[accessibility] Improve Keyboard Navigation

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1779]
We would like the debugger to be keyboard navigable. 

Descriptions
* proper focus states
* proper <kbd>tab</kbd>, <kbd>arrow</kbd> key navigation 
* proper <kbd>space</kbd>, <kbd>enter</kbd>, <kbd>escape</kbd>

Benefits:
* Help accessibility
* Help power users

Todo List:
- [ ] Can't use keyboard to navigate to secondary panel #1772 
- [ ] Source Tab keyboard navigation #1801
- [x] CommandBar actions not tabbable bug #1773 
- [ ] Add keyboard integration tests
- [ ] navigate to tab and breakpoint close buttons
- [ ] navigate to dropdown menuitems
- [ ] Add docs 

Testing:
- [ ] tests should make sure that you can navigate to the command bar and other sections

Docs:
- [ ] should list tools like [chromelens](http://chromelens.xyz/) that have a tracker for keyboard navigation
- [ ] discuss tabindex practices
- [ ] discuss arialabel practices

CC @clarkbw, @Garbee

**Comment by Garbee** [comment]
[Source Tabs](https://github.com/devtools-html/debugger.html/issues/1801) are also a potential problem with the current setup.

**Comment by jasonLaster** [comment]
closing as this is not a priority before we launch. We are already doing better with keyboard navigation than chrome and atom and we can revisit this post 

It's in the enhancements board
https://github.com/devtools-html/debugger.html/projects/5
