### ISSUE TITLE
[Flow] type utility files

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1785]
Lets add types to our utils:

Here are some [docs](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#flow) on using flow:

Files:
- [x] DevToolsUtils.js
- [x] assert.js
- [x] client.js
- [x] create-store.js
- [x] defer.js
- [x] fromJS.js
- [x] log.js
- [x] makeRecord.js
- [x] path.js
- [x] pause.js
- [x] prefs.js
- [x] pretty-print-worker.js
- [x] pretty-print.js
- [x] redux middleware
  - [x] history.js
  - [x] log.js
  - [x] promise.js
  - [x] thunk.js
  - [x] wait-service.js
- [x] redux-devtools.js
- [ ] editor
  - [ ] index.js
  - [x] source-documents.js
  - [x] source-editor.js 
  - [x] source-search.js
  - [x] build-query.js
- [x] source-map-util.js
- [x] source-map-worker.js
- [x] source-map.js
- [x] source.js
- [x] sources-tree.js
- [x] task.js
- [x] text.js
- [x] utils.js

### Progress

Generated by running `yarn run flow-utils`

![screen shot 2017-01-22 at 10 35 06 am](https://cloud.githubusercontent.com/assets/254562/22183529/8c00a076-e08e-11e6-8d53-845fdc80f834.png)

**Comment by ogryzek** [comment]
I'm starting on the `editor.js`

**Comment by leimd** [comment]
working on promise.js

**Comment by skhanker** [comment]
i'll take log.js

**Comment by flexjames** [comment]
create-store.js has flow implemented.

**Comment by mayank-gupta** [comment]
utils.js is done

**Comment by mayank-gupta** [comment]
sources-tree.js is done

**Comment by arthur801031** [comment]
I'll take pretty-print.js.

**Comment by arthur801031** [comment]
I'll take source-documents.js.

**Comment by jasonLaster** [comment]
I'll grab wait-service and history

**Comment by jasonLaster** [comment]
Here are the remaining utils that could use `flow`

```
 src/actions/navigation.js         | 11 +++++++++--
 src/constants.js                  |  6 ------
 src/feature.js                    |  2 ++
 src/panel.js                      |  0
 src/reducers/index.js             |  4 +---
 src/utils/DevToolsUtils.js        |  2 ++
 src/utils/clipboard.js            |  2 ++
 src/utils/defer.js                |  2 +-
 src/utils/editor/index.js         |  2 ++
 src/utils/log.js                  |  2 +-
 src/utils/object-inspector.js     |  2 ++
 src/utils/redux/middleware/log.js |  2 ++
 src/utils/result-list.js          |  2 ++
 src/utils/scopes.js               |  2 ++
 src/utils/task.js                 |  6 +-----
 src/utils/utils.js                |  5 -----
 ```
 
 and a [patch](https://gist.github.com/30b95ac4802d33b7d01adf98583d7150) to help get started

**Comment by jasonLaster** [comment]
closing this as we've mostly finished up. We should add flow to utils when we touch them

**Comment by jasonLaster** [comment]
Here's a patch for the utils/editor https://gist.github.com/jasonLaster/6bce4fefe93f0f03dd2dd8930c6646ed
