### ISSUE TITLE
[WebTestRunner] All the tests

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1919]
Now that we have a working Test Runner on `localhost:8000/integration` we should port the remaining tests and see if we can make some improvements:

### Steps for converting a test

1. create a new `integrations/test/<file>.js`
2. add it to `tests/runner.js`
3. export it in `tests/tests.js` and import it in the original `mochitest/<file>.js`
4. refactor the test:
  * make it async, change yields to await
  * setup `ctx`, add it to asserts
  * add `dbg` to invokeInTab
  * you need to add a source in `initDebugger` to pause on

### Remaining Tests to port
- [ ] breaking-from-console.js
- [ ] breakpoints.js
- [ ] console.js

### Tests to fix
- [ ] breaking-from-console.js
- [ ] console.js
- [ ] searching.js
- [ ] sourcemaps-bogus.js
- [ ] sourcemaps2.js
- [ ] keyboard-shortcuts.js #2262
- [ ] keyboard_navigation.js #2262

### Tests to add 
- [ ] editor
  - [ ] reveal source
  - [ ] "add watch expression"

### Improvements
- [ ] run on CI
- [ ] prompt user to launch a browser
- [ ] make chrome and node testing better
- [ ] improve reporter
- [ ] check for other running debuggers... it will be flakey when another debugger is connected to the tab

**Comment by codehag** [comment]
I am closing this for now as we have removed the WTR
