### ISSUE TITLE
[EditorSearch] Polish Search

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#1930]
Checklist:

- [x] Clearing the query to an empty string causes a search of empty text.
- [x] the search index starts at 1 and always increments by 1 #1967
- [x] deleting the query does not clear the last match
- [x] white space queries breaks the editor
- [x] queries increment the searches #2046
- [x] can't delete the last letter of the query
- [x] clicking in the document does not update the search index #2065
- [x] Editor Search breaks with "whole word" modifier and query's of 3 or less characters #2105 
- [ ] escape should always close the search bar #2104 @nchevobbe 
- [x] cmd+f without a selection should refocus the search bar #2103 
- [x] search jumps #2081
- [ ] Add integration tests #1928
- [x] move search state to UI reducer #2126 
- [x] Add search bottom bar #2078 
- [x] Refactor search components to better support function search in editor. #2151 
- [x] doSearch slowness #2154 
- [x] Only do one search type #2171 
- [x] polish overlays #2228

**Comment by arthur801031** [comment]
I'll try to take a stab at "Clearing the query to an empty string causes a search of empty text.".

**Comment by arthur801031** [comment]
Hi @wldcordeiro!

I can't reproduce this bug: "Clearing the query to an empty string causes a search of empty text". Please let me know how to reproduce it. Thank you! 😀
![2c31hesfrz](https://cloud.githubusercontent.com/assets/4562118/22810033/294e56de-ef71-11e6-8d97-543dd306c74a.gif)

**Comment by jasonLaster** [comment]
Thanks @arthur801031. I couldn't find that either. But it did help me find two others :)

- [ ] deleting the query does not clear the last match
- [ ] white space queries breaks the editor

![](http://g.recordit.co/TNaR3tONHH.gif)

**Comment by arthur801031** [comment]
Hi @jasonLaster 

For "deleting the query does not clear the last match" bug, the Chrome debugger also has this behavior, but it changes the highlight color for the last character that was cleared. Maybe we should change the yellow to something else?

![zdmwbp0w6h](https://cloud.githubusercontent.com/assets/4562118/22966296/84bcd0a2-f39c-11e6-93fb-630f7217e5e0.gif)

**Comment by jasonLaster** [comment]
closing this as we've done all of the big work here
