### ISSUE TITLE
[Flow] Get good coverage across the board (V2)

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1935]
We recently succeeded in reaching out MVP goal of having coverage in every part of the component. For this new goal, we want to have good coverage across the board:

- [ ] add flow coverage to utility files #1785
- [x] add flow to components #1894 (we don't need to type all components)
- [ ] actions 80% 
- [ ] reducers 80%
- [ ]  flow types for `react-dom` functions

**Comment by jasonLaster** [comment]
closing this as we've added Flow to almost all the files. We can prioritize more coverage when we have codecov and other work done
