### ISSUE TITLE
Function Search

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2007]
This is a tracking issue for source function search. It's a really cool feature where we'd love to get some help! If you're interested in helping, ask in the issue and you can take one of the items.

### Checklist

- [x] find functions in search util #1846
- [x] function search UI POC #1995 
- [x] function search UI (for real) #1845 
- [x] move to the SearchBar component #2066
- [x] support scrolling the list of results #2106
- [x] move function declarations out of editor state and to the util #2124
- [x] remove search handler on componentUnMount #2125 
- [x] Clean up styling of result scrolling #2169 
- [x] Only do one search type #2171 
- [x] Add result summary for function search #2172 
- [x] Polish the Search for UI #2203
- [x] Chrome search bar jumps #2204
- [x] Polish the search line positioning #2205
- [x] Fix sad face #2206
- [x] Polish toggling searches #2208

**Comment by wldcordeiro** [comment]
We got the whole list so I'm closing this. If we have reason to reopen we will.
