### ISSUE TITLE
[WatchExpressions] Polish

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2107]
**Checklist**:
- [x] Double check refresh watch expressions
- [x] vertically align "Add Watch Expression" #2123
- [x]  error when adding an expression #2112

**Comment by clarkbw** [comment]
The text is not vertically aligned.

![screen shot 2017-02-23 at 9 01 07 am](https://cloud.githubusercontent.com/assets/2134/23269814/a5ac69c0-f9a6-11e6-9b5a-9f33c892e935.png)

**Comment by zystvan** [comment]
@wldcordeiro I'll try to align the "Add Watch Expression" text vertically.

**Comment by wldcordeiro** [comment]
The issues in the list were done. Closing.
