### ISSUE TITLE
[Sources] use file type icons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2545]
We can use the icon font that atom uses for its source tree

- [x] React Components - #2690 [badge](https://vorillaz.github.io/devicons/#/singleicon/react) [1]
- [x] JavaScript - [badge](https://vorillaz.github.io/devicons/#/singleicon/javascript_badge)
- [x] Webpack - source map domains. We'll need to get an SVG
- [ ] Style the tree now that we have some icons
- [x] style the webpack icon #2859

[1] We can be conservative and only highlight component files.
  1. use babel to find a file that uses `createClass` or extends `Component`.
  2. check the file path to see if it is in a component dir...
  
  ---

- https://vorillaz.github.io/devicons/#/dafont
- we can likely use dafont's SVGs instead of using the font library and getting webpack to work.

**Comment by irfanhudda** [comment]
Do we want to display different icons for `.jsx` files or coffeescript files in source tree of debugger instead of generic file icons?

**Comment by jasonLaster** [comment]
@wldcordeiro is on it
