### ISSUE TITLE
Release Debugger.html

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2586]
This is the issue to track all of the tickets that we want to complete before releasing Firefox 56 (April ???)

**Comment by jasonLaster** [comment]
#### Features
- [ ] [FunctionSearch] 'Search for:' in search filter bar not localizable/hardcoded/always in English #2555
- [ ] [EditorPreview] support outer scope expressions #2536
- [ ] [PreviewPopup] Position it intelligently #2565
- [ ] [Scopes] group window default properties #2280

#### Nice to Haves

- [ ] Framework Annotations #2570
- [ ] [Sources] use file type icons #2545
- [ ] [scopes] Format functions labels #2434

**Comment by jasonLaster** [comment]
We're no longer following this list. And yeah - we've done all the items too :)
