### ISSUE TITLE
CodeFolding

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2588]
We added basic code folding in #2468, but it is missing some functionality before it can land:

- [ ] hide fold markers unless hovering on the gutter
- [ ] style the fold markers like Atom
  - [x] update the marker styles
  - [ ] style closed markers like Atom
- [ ] highlight the folded markers specially
- [ ] paused lines get clipped by the fold gutter
- [ ] clicking in the fold gutter should add a breakpoint if there isn't a fold marker...

### How to test folding

Go to the settings panel and enable "code folding"

### Styling closed markers

1. use the devtools orange theme
2. update the devtools collapse icon to be similar to atoms...
  note cmd+option+i in atom opens atom's devtools! you can steal their collapse badgey thing 

<img width="633" alt="screen shot 2017-04-11 at 3 39 00 pm" src="https://cloud.githubusercontent.com/assets/254562/24927463/21cb33e2-1ecd-11e7-8067-9d9c7bb305bd.png">

**Comment by jasonLaster** [comment]
I think we could do something where you hide the fold markers by default and only show them if the gutter is hovered `gutter::hover .fold-marker { display: block } ` if that doesn't work, on gutter hover we add a class the the fold marker parent element...

**Comment by AnshulMalik** [comment]
I did some experimentation to implement ` hide fold markers unless hovering on the gutter`. But seems like using only css doesn't work.

**Comment by irfanhudda** [comment]
@AnshulMalik Yes. Looks like using just CSS to "hide _all_ fold markers unless hovering on gutter" may not work because of their placement in DOM tree and limitation of CSS selectors.(I might be wrong here)

I could get a crude version working using `eventListeners`

**Comment by jasonLaster** [comment]
@irfanhudda mind PRing the crude version.

@AnshulMalik I'll review your styling independently

**Comment by wldcordeiro** [comment]
> Yes. Looks like using just CSS to "hide all fold markers unless hovering on gutter" may not work because of their placement in DOM tree and limitation of CSS selectors.(I might be wrong here

@irfanhudda I was trying to do this as well, it's complicated. The "gutter" itself lives at a different level in the tree than the markers. I think there  is likely some really specific CSS selector like (pseudo selectors here) `.gutter:hover ~ .gutter-elems .hover-marker`. If you find a good solution I'd love to see it! 😄

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue
