### ISSUE TITLE
[Breakpoints] Column Breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2787]
We recently landed the Proof of Concept column breakpoints feature in #2760. Now we need to 

- [x] style the marker #2786
- [x] add a parser function for getting the valid callsites on a line #2788
- [ ] work on the UX (maybe something closer to chromes)? #3254
- [ ] Show good gutter markers for breakpoints #3295
- [ ] Remove breakpoints on click and alt + click #3296

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue
