### ISSUE TITLE
Outline View

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2901]
This issue tracks our progress towards being able to ship an Outline View in the left sidebar.

There are lots of small tidy up tickets here that anyone can grab

#### Checklist

- [x] [OutlineView] Navigation #2563
- [x] [Parser] get function params #2735
- [ ] adding an "Outline" label in the header
- [x] Switching the footer toggle button to tabs 
- [x] Replace blue bullet with something better
- [ ] ship it

#### Switching the footer toggle button to tabs 

We currently have a toggle button, but it would be nice to show both of them side by side like what we do in the editor footer for pretty printing and black boxing. We can borrow the same aria tooltip strategy from there too!

#### Replace blue bullet with something better

So... the outline items could look better. Lets tweak the hover behavior and style. I'm thinking cursor pointer, slight hover background perhaps. Maybe borrow from function search results or the call stack. Also of course the look and feel of the functions :)

#### GIF
![toggle](https://cloud.githubusercontent.com/assets/7821757/26278262/8321bf9e-3db3-11e7-913b-fde6a07841c3.gif)

**Comment by rohanprasad** [comment]
@jasonLaster Is this done ?

**Comment by jasonLaster** [comment]
@rohanprasad yeah, this was V1 and we can consider it done
