### ISSUE TITLE
Editor Variable Preview 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2903]
This issue tracks the work needed to release editor variable previews.

### Checklist

- [x] [Preview] Function names should be simplified  #2891
- [x] [Preview] We shouldn’t wrap function tooltips #2898
- [x] [Preview] Slide popup horizontally so that it fits in the UI #2899
- [x] [Preview] don’t show optimized away values #2908

### Nice to have

**Comment by bomsy** [comment]
These are all done!
