### ISSUE TITLE
Lint the text in our docs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2971]
We're currently using the fantastic [remark], which is part of [unified] for linting our markdown structure. [unfied] also offers linters for the language in our docs through [retext]. [Plugins][plugins] include checks for duplicate words, passive voice, gendered nouns, and many other great checks.

It would be great to add [retext] and start linting our language.

*   [`dunckr/retext-cliches`](https://github.com/dunckr/retext-cliches) — Check phrases for cliches;
*   [`wooorm/retext-contractions`](https://github.com/wooorm/retext-contractions) — Check apostrophe use in contractions;
*   [`wooorm/retext-diacritics`](https://github.com/wooorm/retext-diacritics) — Check for proper use of diacritics;
*   [`wooorm/retext-english`](https://github.com/wooorm/retext/tree/master/packages/retext-english) — English language support;
*   [`wooorm/retext-emoji`](https://github.com/wooorm/retext-emoji) — Encode or decode [Gemojis](https://github.com/github/gemoji);
*   [`wooorm/retext-equality`](https://github.com/wooorm/retext-equality) — Warn about possible insensitive, inconsiderate language;
*   [`wooorm/retext-indefinite-article`](https://github.com/wooorm/retext-indefinite-article) — Check if indefinite articles (`a`, `an`) are used correctly;
*   [`dunckr/retext-overuse`](https://github.com/dunckr/retext-overuse) — Check words for overuse;
*   [`wooorm/retext-passive`](https://github.com/wooorm/retext-passive) — Check for passive voice;
*   [`wooorm/retext-profanities`](https://github.com/wooorm/retext-profanities) — Check profane and vulgar wording;
*   [`wooorm/retext-readability`](https://github.com/wooorm/retext-readability) — Check readability;
*   [`wooorm/retext-redundant-acronyms`](https://github.com/wooorm/retext-redundant-acronyms) — Check redundant acronyms (`ATM machine` > `ATM`);
*   [`wooorm/retext-repeated-words`](https://github.com/wooorm/retext-repeated-words) — Check `for for` repeated words;
*   [`wooorm/retext-sentence-spacing`](https://github.com/wooorm/retext-sentence-spacing) — Check spacing between sentences;
*   [`wooorm/retext-simplify`](https://github.com/wooorm/retext-simplify) — Check phrases for simpler alternatives;
*   [`wooorm/retext-smartypants`](https://github.com/wooorm/retext-smartypants) — Implementation of [SmartyPants](http://daringfireball.net/projects/smartypants/);
*   [`wooorm/retext-spell`](https://github.com/wooorm/retext-spell) — Spelling checker;
*   [`wooorm/retext-stringify`](https://github.com/wooorm/retext/tree/master/packages/retext-stringify) — Compile back to text;
*   [`wooorm/retext-syntax-mentions`](https://github.com/wooorm/retext-syntax-mentions) — Classify `@mentions` as syntax;
*   [`admhlt/retext-usage`](https://github.com/admhlt/retext-usage) — Check incorrect English usage;
*   [`wooorm/retext-quotes`](https://github.com/wooorm/retext-quotes) — Check quote and apostrophe usage.

[retext]:https://github.com/wooorm/retext
[plugins]:https://github.com/wooorm/retext/blob/master/doc/plugins.md
[unified]:https://unifiedjs.github.io/
[remark]:https://github.com/wooorm/remark

**Comment by jasonLaster** [comment]
I made a quick branch w/ @wooorm here: https://github.com/jasonLaster/devtools-linters/blob/master/bin/prose.js

**Comment by jasonLaster** [comment]
We've started linting the text in devtools-linters. See these issues: https://github.com/jasonLaster/devtools-linters/issues

**Comment by jasonLaster** [comment]
- [ ]	Add gender checking	jasonLaster/devtools-linters#9	 
- [ ]	Enable spell checking	jasonLaster/devtools-linters#5	 
- [ ]	Enable checking for repeated words	jasonLaster/devtools-linters#8	 
- [ ]	Enable quote checking	jasonLaster/devtools-linters#7	 
- [ ]	Enable sentence spacing checks	jasonLaster/devtools-linters#6
