### ISSUE TITLE
SourceMaps in the client

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#307]
This is a tracking Issue for the source map work.

Planned Tickets (sprint 1):
- [x] #305 - Load source map files locally
- [x] #306 - Create Sources with the source map consumer
- [x] #304 - Show source map files in the tree
- [x] #303 - Show source map files in the editor

Planned Tickets (sprint 2):
- [x] set breakpoints
- [x] #336 show paused state
- [x] #328 show root path domains

Planned Tickets (sprint 3)
- [x] client-side pretty printing
- [ ] load source map files in the toolbox

There's plenty of work that's not yet planned:
- show breakpoints in the generated source
- support breakpoints being loaded from local storage (before the new source map has loaded)...
- support creating source map consumers/nodes in a web worker

**Comment by jasonLaster** [comment]
Closing this issue as it's largely done and opening an issue for https://github.com/devtools-html/debugger.html/issues/469
