### ISSUE TITLE
Update outdated modules

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3141]
With #3134 we changed our `yarn.lock` updater.  I believe we've been seeing a number of issues with greenkeeper because of the old code.  I'd like to review and update some of our deps in a new PR to get us running on the stable version of modules we might have missed with recent greenkeeper PRs.

Working on:

- [x] firefox-profile removed in #3142
- [x] prettier updated to 1.4.4 in  #3142
- [x] percy-io/react-percy-storybook updated to 0.1.11 in #3142
- [x] flow-bin  #3012 lots of errors to deal with here
- [ ] babel-types not sure about this, currently seems broken #3140
- [ ] babel-traverse not sure about this, currently seems broken #3143
- [ ] svg-inline #2653 is difficult because so much has changed, it went esnext on us and doesn't ship a transpiled version which breaks at least the tests https://github.com/sairion/svg-inline-react/compare/v1.0.3...master

Ignoring for now
- [x] react related modules are to stay at their current versions
- [x] webpack is going to be a long process to get to 2.0 #3004
- [x] workerjs is a GH dep so we can ignore it

```
$ yarn outdated
yarn outdated v0.24.6
Package                         Current Wanted Latest Package Type    URL                        
@percy-io/react-percy-storybook 0.1.10  0.1.11 0.1.11 dependencies                               
babel-traverse                  6.24.1  6.25.0 6.25.0 dependencies                               
babel-types                     6.24.1  6.25.0 6.25.0 dependencies                               
firefox-profile                 0.4.9   0.4.9  1.0.0  dependencies                               
flow-bin                        0.46.0  0.46.0 0.47.0 dependencies                               
jest-localstorage-mock          1.1.1   1.2.0  1.2.0  devDependencies                            
prettier                        1.4.2   1.4.4  1.4.4  dependencies                               
react                           15.3.2  15.3.2 15.5.4 dependencies                               
react-addons-perf               15.3.2  15.3.2 15.4.2 devDependencies                            
react-addons-test-utils         15.3.2  15.3.2 15.5.1 devDependencies                            
react-dom                       15.3.2  15.3.2 15.5.4 dependencies                               
svg-inline-react                1.0.3   1.0.3  2.1.0  dependencies                               
webpack                         1.14.0  1.14.0 2.6.1  dependencies                               
workerjs                        0.1.2   exotic exotic dependencies    github:jasonLaster/workerjs
```

**Comment by clarkbw** [comment]
The [firefox-profile](https://www.npmjs.com/package/firefox-profile) module seems suspicious and I can't find where we are using it.

```
$ yarn why firefox-profile
yarn why v0.24.6
[1/4] 🤔  Why do we have the module "firefox-profile"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "firefox-profile"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "428kB"
info Disk size with unique dependencies: "6.91MB"
info Disk size with transitive dependencies: "8.29MB"
info Number of shared dependencies: 34
✨  Done in 1.42s.
```

**Comment by jasonLaster** [comment]
oh thanks. you might want to use a package like: https://www.npmjs.com/package/orphan or https://www.npmjs.com/package/depcheck to find the orphaned packages. I stole this trick from tofino

**Comment by clarkbw** [comment]
Here's what a test run looks like when the svg-inline-react is updated.

```
$ yarn test
yarn test v0.24.6
$ jest 
 FAIL  src/components/Editor/tests/Editor.js
  ● Test suite failed to run

    /Users/clarkbw/src/mozilla/debugger.html/node_modules/svg-inline-react/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (assets/images/Svg.js:2:17)
      at Object.<anonymous> (src/components/shared/Svg.js:6:12)
```

**Comment by zaggy** [comment]
Hi, I've updated flow-bin, but I just plugged `any` everywhere, which is bad taste, I suppose, we need another ticket for fighting with `any` throughout the code base. Also, there are 4  mistakes coming from launchpad, for which I will push a PR today for.

**Comment by clarkbw** [comment]
Closing this out for now.  We've updated most of the easier modules.  The rest are larger infrastructure projects that could use their own tracking issue if someone wanted to tackle it.
