### ISSUE TITLE
[Breakpoints] AST Breakpoints

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3150]
Here is a [writeup] on AST Breakpoints

[writeup]:https://docs.google.com/document/d/1o3xVV_rTe-oxH7ujYUJ4a_XKSdPo1udVO7rKAfdas44/edit

### TODO
- [x] astLocation util that uses symbols
- [x] add astLocation field
- [x] add astLocation to addBreakpoint
- [x] clear ast tree [BUG] 
- [x] update syncBreakpoint to delete server breakpoints on sync if an ast breakpoint location is valid
- [x] update syncBreakpoiint to add an ast located breakpoint if available
- [ ] mochi tests

**Comment by codehag** [comment]
Hiya!

I was playing around with this already. here is some very messy old code (in case anyone is looking for a starting point)

```diff
diff --git a/src/actions/breakpoints.js b/src/actions/breakpoints.js
index 32be0377..45587b50 100644
--- a/src/actions/breakpoints.js
+++ b/src/actions/breakpoints.js
@@ -12,6 +12,7 @@ import { PROMISE } from "../utils/redux/middleware/promise";
 import { getBreakpoint, getBreakpoints, getSource } from "../selectors";
 import { originalToGeneratedId } from "devtools-source-map";
 import { equalizeLocationColumn } from "../utils/breakpoint";
+import { getClosestPath } from "../utils/parser/utils/closest";

 import type { ThunkArgs } from "./types";
 import type { PendingBreakpoint, Location } from "../types";
@@ -220,11 +221,54 @@ export function addBreakpoint(
     }

     const breakpoint = _createBreakpoint(location, { condition });
+    const bp = _getOrCreateBreakpoint(getState(), location, condition);
+
+    let updatedLocation;
     return dispatch({
       type: "ADD_BREAKPOINT",
       breakpoint,
       condition: condition,
-      [PROMISE]: addClientBreakpoint(getState(), client, sourceMaps, breakpoint)
+      // NOT TO BE USED: just plaing around with AST
+      [PROMISE]: (async function() {
+        if (sourceMaps.isOriginalId(bp.location.sourceId)) {
+          const source = getSource(getState(), bp.location.sourceId);
+          updatedLocation = await sourceMaps.getGeneratedLocation(
+            bp.location,
+            source.toJS()
+          );
+        }
+
+        let { id, actualLocation, hitCount } = await client.setBreakpoint(
+          updatedLocation,
+          bp.condition,
+          sourceMaps.isOriginalId(bp.location.sourceId)
+        );
+
+        actualLocation = await sourceMaps.getOriginalLocation(actualLocation);
+
+        const blah = getClosestPath;
+        const source = getSource(getState(), bp.location.sourceId);
+        const originals = await sourceMaps.getOriginalSourceText(source.toJS());
+        const closestcurrent = getClosestPath(originals, bp.location);
+        const closestactual = getClosestPath(originals, actualLocation);
+        console.log("nodes", location.node, closestactual.node);
+        console.log("nodes", location.node === closestactual.node);
+        console.log("full", closestactual);
+        console.log(bp.location, actualLocation);
+        // If this breakpoint is being re-enabled, it already has a
+        // text snippet.
+        let text = bp.text;
+        if (!text) {
+          text = getTextForLine ? getTextForLine(actualLocation.line) : "";
+        }
+        return {
+          id,
+          actualLocation,
+          closestactual: closestactual.node,
+          text,
+          hitCount
+        };
+      })()
     });
   };
 }
```

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/actions/ast.js b/src/actions/ast.js
index 4784f9b..6ab8878 100644
--- a/src/actions/ast.js
+++ b/src/actions/ast.js
@@ -35,6 +35,8 @@ export function setSymbols(sourceId: SourceId) {
       source,
       symbols
     });
+
+    correctBreakpointLocations();
   };
 }

diff --git a/src/actions/breakpoints.js b/src/actions/breakpoints.js
index efa4638..dbd84ea 100644
--- a/src/actions/breakpoints.js
+++ b/src/actions/breakpoints.js
@@ -354,3 +354,13 @@ export function toggleDisabledBreakpoint(line: number, column?: number) {
     return dispatch(enableBreakpoint(bp.location));
   };
 }
+
+export function correctBreakpointLocations(sourceId: string) {
+  return async ({ dispatch, getState, client, sourceMaps }: ThunkArgs) => {
+    // get the symbols for the source
+    // get the breakpoints for the source
+    // loop over the breakpoints and check to see if their AST location is different
+    // than their original location
+    // if it is, then remove the breakpoint and re-add it
+  };
+}
```
