### ISSUE TITLE
[Search] Switch to Editor style UX

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3178]
We have a couple search idiosyncrasies at the moment. 

1. [ ] File Search is on the top and not the bottom
2. [x] Function Search is associated (not a modal)
3. [x] Source Search is its own pane (not a modal)
4. [x] Merge modals into one (symbol, sources, go-to-line)
4. [ ] Project Search is its own pane (not in the bottom w/ a separate results tab)

We should land project text search and then clean up the UX holistically.

**Comment by jasonLaster** [comment]
![Screen Shot 2017-09-27 at 8.10.37 PM.png](https://shipusercontent.com/f6c10d9f44203f1e2f6c8c24d3ec53c9/Screen%20Shot%202017-09-27%20at%208.10.37%20PM.png)
![Screen Shot 2017-09-27 at 8.10.26 PM.png](https://shipusercontent.com/f50ae61ebd1f6e3a86b95b15bb71da57/Screen%20Shot%202017-09-27%20at%208.10.26%20PM.png)

**Comment by wldcordeiro** [comment]
I totally want to get into this after the redux stuff lands. 😄

**Comment by wldcordeiro** [comment]
Updating the task list a bit. I'd like to flesh this out further to outline the steps.

**Comment by wldcordeiro** [comment]
Resources for implementing `GoToAnythingModal`

* http://docs.sublimetext.info/en/latest/file_management/file_navigation.html#goto-anything
* http://flight-manual.atom.io/using-atom/sections/moving-in-atom/

Overview.

* `@` prefix does symbol search
* `#` does term search
* `:<line>:<column` goes to line in current file
* *maybe* `model:30:20` first search for a file whose path matches models, and then to go to line 30 in said file.

**Comment by jasonLaster** [comment]
@wldcordeiro didn't realize that this checklist was being updated!

**Comment by jasonLaster** [comment]
Here's a great starting off point: https://github.com/devtools-html/debugger.html/pull/4199

**Comment by jasonLaster** [comment]
I'm moving this to the icebox as it is nice, but not on the roadmap
