### ISSUE TITLE
Symbol Modal Follow-Ups

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#3231]
- [x] clicking out of the modal closes it #3232 
- [ ] add button to file search to open symbol search #3233 
- [x] animate the symbol search enter/leave #3234 
- [ ] `*` as only char in search input returns list of all symbols in file #3235 
- [ ] search results shouldn't show sad face for `@`/`#`/`*` until additional chars typed. #3236

**Comment by jasonLaster** [comment]
closing for now as we're not going to do this follow up
