### ISSUE TITLE
[Editor] Refactor CodeMirror Children

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3264]
In SF we discussed a strategy for compartmentalizing our codemirror editor logic in terms of HoCs. This is the strategy we use for breakpoints and highlighted lines

#### Tasks: 

- [x] Breakpoints [file](https://github.com/asolove/debugger.html/blob/editor-components/src/components/Editor/Breakpoint.js#L1)
- [x] Highlight Lines [file](https://github.com/asolove/debugger.html/blob/editor-components/src/components/Editor/HighlightLines.js#L1)
- [x] Debug Line [pr](https://github.com/devtools-html/debugger.html/pull/3255)
- [x] preview popup [pr](https://github.com/devtools-html/debugger.html/pull/3749)
- [ ] Text [gist](https://gist.github.com/jasonLaster/fe6ce6af67e1ed351cfdc803f56c5db4)
- [ ] HighlightLine [gist](https://gist.github.com/5cc88075446671ac56c13665352e1dac)
- [ ] Conditional BP Panel [gist](https://gist.github.com/0c4e04ce5bcb16b9e7bd91012b024718) 
- [ ] Gutter Menu might be nice too

#### Rationale:

This will help untangle some logic and improve readability and testing.

**Comment by jasonLaster** [comment]
@asolove and I talked offline and had some interesting takeaways:

1. CodeMirror children implicitely depend on the codemirror document being set. i.e. breakpoints should be added after the document is set. This means that the Editor document should be set in component will receive props and the breakpoints should be set in in component did update. We can have some assertions that guard against mistakes.

2. CodeMirror perf comes from using codemirror's operation method. The API is a callback `cm.operation(() => {})`. It would be nice to use CM's two low level methods startOperation and endOperation.

3. It's possible that two children might have some state dependencies that will need to move up to redux. This is generally nice. With that said, we should be careful because sometimes we fire actions that don't change the state.

**Comment by jasonLaster** [comment]
I'm going to close this issue because we're continuing to make progress on refactoring the editor.

Our plan is to refactor a feature before we work on it. We did this w/ debugLine and it worked well.

Most of our tracking issues are for large features or lots of small refactorings. This is a large code health project with a lot of risk, so it doesn't feel right to keep a tracking issue open for it.
