### ISSUE TITLE
Mochi Runner

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3660]
The Mochi CLI is a mochitest wrapper designed to make running mochitests a more enjoyable pleasant experience. Two goals of the project are to 

a) smooth over rough edges introduced from the launchpad setup
b) focus on the 90% case and remove a lot of the noise that is not necessary for debugging a JS error.

#### Runner

- [ ] Fail when firefox needs to be rebuilt
- [ ] Have a prompt when the test finishes to re-run the test
- [ ] Wrap `yarn copy-assets-watch` so that users don't need two terminals
- [ ] use local config (see below)

#### Reporter

- [ ] show progress before the first test starts
- [ ] hide output for tests that pass
- [ ] use more emojis or update text inline

#### Screenshot

<img src='https://shipusercontent.com/75bdb29f1a06425bf5080b525125a725/Screen%20Shot%202017-08-14%20at%202.44.34%20PM.png' title='Screen Shot 2017-08-14 at 2.44.34 PM.png' width=1341>

##### Use local config
We are currently using a hardcoded directory for `yarn mochi`, we should instead rely on what is set in the config

```diff
diff --git a/bin/mochi.js b/bin/mochi.js
index e8c08fc3..108284ee 100644
--- a/bin/mochi.js
+++ b/bin/mochi.js
@@ -248,6 +248,7 @@ async function startWebpack() {
 }
 
 function runMochitests(args) {
+  // use the config from configs/local.json
   shell.cd("firefox");
   const command = `./mach mochitest ${args.join(" ")}`;
   console.log(chalk.blue(command));
```

**Comment by jasonLaster** [comment]
[title](url)

**Comment by jasonLaster** [comment]
The jest CLI is built here: https://github.com/facebook/jest/blob/ab6f4c3001a2cd917cc4df95e42dfc72f23c5a00/packages/jest-cli/src/watch.js#L318-L323

**Comment by jasonLaster** [comment]
Here's a sketch for a prompt when mochi finsihes

```diff

diff --git a/bin/mochi.js b/bin/mochi.js
index f7cb119..a50c342 100644
--- a/bin/mochi.js
+++ b/bin/mochi.js
@@ -268,6 +268,21 @@ function runMochitests(args) {
       }
     });
   });
+
+  child.then(code => printCLI())
+}
+
+function printCLI() {
+  console.log(`Press r to re-run`)
+  console.log(`Press q to quit`)
+  const r = process.prompt()
+  console.log(r)
+
+  if (r == "r") {
+    runMochitests()
+  } else {
+    shell.exit()
+  }
 }

 async function run(args) {
@@ -282,7 +297,7 @@ async function run(args) {

   // TODO: it would be nice to automate the full workflow so users can
   // run one test and then be able to kill the run and re-run. kinda like jest --watch
-  // await startWebpack()
+  await startWebpack()

   runMochitests(args);
 }
 ```

**Comment by codehag** [comment]
I merged in the current branch, what is the status here? can we clsoe?
