### ISSUE TITLE
Async Stepping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3807]
This is a tracking issue for supporting async stepping

```js
1.    async foo() {
2.      await bar();
3.      return true;
4.   }
```

- [x] land a test for step over (might need to tweak the implementation)
- [ ] add support for step in and step out
- [ ] add unit tests for the new parser functions
- [ ] add support for stepping over the last statement
