### ISSUE TITLE
Worker List

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3815]
- [x] Show list of Workers (React) #3701
- [x] Get the worker list data (Redux) #3814
- [x] Show Worker data in the component (React-redux)
- [x] Update the list or workers when it changes (Add workerListchanged)
- [x] Add the link to open a new worker toolbox #4033 
- [x] Listen for new workers and add them to the list

**Comment by jasonLaster** [comment]
This work is nearly done here: https://github.com/devtools-html/debugger.html/pull/4258

**Comment by captainbrosset** [comment]
Something to keep in mind when working on this feature: we used to have a pretty bad crash when opening a worker's script. See this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1260239
We should test this scenario again when this is available.

**Comment by jasonLaster** [comment]
I just started looking into listening for worker list change events

```diff
diff --git a/src/client/firefox/events.js b/src/client/firefox/events.js
index 250c7a1..acb2cca 100644
--- a/src/client/firefox/events.js
+++ b/src/client/firefox/events.js
@@ -82,10 +82,13 @@ function newSource(_: "newSource", { source }: SourcePacket) {
   }
 }
 
+function workerListChanged(a, b, c) {debugger;}
+
 const clientEvents = {
   paused,
   resumed,
-  newSource
+  newSource,
+  workerListChanged
 };
 
 export { setupEvents, clientEvents };
```

So far it's not working :)
