### ISSUE TITLE
Chrome Debugging

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3947]
This is a tracking issue for debugging Chrome/V8.

- [ ] show variables #2443
- [ ] issues with breakpoints #3562
- [ ] it shows numbers as [Object object] #3002
- [ ] Anonymous functions not labelled in call stack #2878

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue
