### ISSUE TITLE
[Breakpoints] address syncing edgecases

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3982]
We are seeing issues w/ breakpoints entering a corrupted state where we cannot remove them.

We should make sure we cover all the possible edge cases here and have test coverage.

#### User scenarios
* add a new BP
* reload debuggee 
* open / close debugger

#### Debugger Scenarios

* mapping is not symmetric (O->G) ≠ (G->O)
* bp slides when being added in the server
* client has a different location than reducer
* prefs saved a bad value

**Comment by codehag** [comment]
do we have more specific scenarios here? this looks like it should be split into smaller tickets

**Comment by jasonLaster** [comment]
Moving this to a tracking issue so that we can add some specific issues below it

**Comment by jasonLaster** [comment]
closing as we do not have a specific STR... and we fixed a syncing issue last week that could have been the root cause.

**Comment by jasonLaster** [comment]
So far I see a couple of interesting cases:

- [ ] keep disabled bps in sync when the source changes
- [ ] remove bps when they no longer map to a generated location
- [ ] remove bps when they move from the module scope to a function scope
- [ ] key bp clients by ID and not location
