### ISSUE TITLE
[Shortcuts] modal polish

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4213]
#### Todos

- [ ] we should add a shortcut for launching it via `cmd + /` i think
- [ ] we should move K+ to the right and soften the color (whatever the accordion headers are)
- [ ] the section headers in the mocks looked pretty nice. Lets do some small typography cleanup.

```diff
diff --git a/src/components/App.js b/src/components/App.js
index 1dd5132..62f5b35 100644
--- a/src/components/App.js
+++ b/src/components/App.js
@@ -100,6 +100,9 @@ class App extends Component {
       L10N.getStr("symbolSearch.search.key2"),
       this.toggleSymbolModal
     );
+
+    shortcuts.on(shortcutModalKey, this.toggleShortcutsModal);
+
     shortcuts.on("Escape", this.onEscape);
   }

diff --git a/src/components/SecondaryPanes/index.js b/src/components/SecondaryPanes/index.js
index 55cd6f9..174f661 100644
--- a/src/components/SecondaryPanes/index.js
+++ b/src/components/SecondaryPanes/index.js
@@ -222,6 +222,7 @@ class SecondaryPanes extends Component {
       return;
     }

+    // we can style this in utils bar.css
     return (
       <UtilsBar
         horizontal={this.props.horizontal}
diff --git a/src/components/ShortcutsModal.css b/src/components/ShortcutsModal.css
index b3edaaa..c29b771 100644
--- a/src/components/ShortcutsModal.css
+++ b/src/components/ShortcutsModal.css
@@ -5,6 +5,7 @@
   column-width: 250px;
 }

+/* HERE */
 .shortcuts-content h2 {
```

**Comment by codehag** [comment]
K+ is not clear in my opinion. perhaps we should write it out, or use `?` for help or something like this?

**Comment by jasonLaster** [comment]
Yeah, now that you say it I think `?` is a more universal button for shortcuts

**Comment by jasonLaster** [comment]
Here is the design for shortcuts. I think the only thing style wise is the headers

![](https://user-images.githubusercontent.com/55994/30822975-9ab5ff7c-a1df-11e7-80ee-7c486667a416.png)
