### ISSUE TITLE
Photon UI follow up

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4312]
We recently did a photon visual ui overhaul, here are some follow up items. Feel free to claim one

#### Tasks

- [x] Remove tabs "+" button
- [ ] Re-think the tabs show more dropdown :question: 
- [ ] Re-think collapse buttons :question: 
- [x] Update Watch expressions input :smiley:
- [x] Update the look of matching brackets highlight for Photon #4217

#### Screenshots

![Screen Shot 2017-10-06 at 4.42.15 PM.png](https://shipusercontent.com/79b25a684e14b54b5da738ef6e8396e8/Screen%20Shot%202017-10-06%20at%204.42.15%20PM.png)

#### Collapse buttons

The current collapse buttons take up visual space and feel a bit dated. Do we want to consider using Atom's collapse UI:

![Screen Shot 2017-10-06 at 4.39.27 PM.png](https://shipusercontent.com/f307a7030b5512c0b135e93cddb074f0/Screen%20Shot%202017-10-06%20at%204.39.27%20PM.png)

**Comment by MFry** [comment]
@jasonLaster I can't tell from the photos the "+" you are talking about.  Could I get more info and I will work on it.

**Comment by jasonLaster** [comment]
The new tab "+"

<img src='https://shipusercontent.com/14f9584645cf237bdc2c3bef48f54dc1/Screen%20Shot%202017-10-10%20at%2010.26.35%20PM.png' title='Screen Shot 2017-10-10 at 10.26.35 PM.png' width=725>

**Comment by steveck-chung** [comment]
@jasonLaster Is there any photon spec for input behavior? Because the placeholder for watch expressions seems fine right now.

**Comment by jasonLaster** [comment]
hmm... i think the input is okay. I suppose we're thinking about the UI when it's not focused.

**Comment by jasonLaster** [comment]
Closing this as this represents the work down last fall. Lets open a new photon UI for this next sprint.
