### ISSUE TITLE
Pretty Print Issues

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4453]
A few issues I've identified with the pretty print functionality at this point:

- [x] Clicking the pretty print icon doesn't focus on the newly created pretty print tab #4647
- [x] Clicking on the pretty print tab un-focuses the source in the Sources Tree tab.
- [x] Right-clicking a line in the pretty-printed source and clicking "Jump to Generated location" doesn't highlight the line or focus the cursor on said line.
- [x] Clicking the "Jump to Generated source" item switches to the original source tab but the lines column is AWOL:
- [x] Pretty tab does not go away #4714

<img width="722" alt="wheredalinesat" src="https://user-images.githubusercontent.com/46655/31846823-8f8ed71c-b5d6-11e7-8646-7f95925b17f7.png">

**Comment by jasonLaster** [comment]
lol I've never seen the columns just bounce

**Comment by bomsy** [comment]
@darkwing @jasonLaster i've also noticed the column doing the disappearing acts too ...lol

**Comment by darkwing** [comment]
IMO this should lean toward P1-ish -- not focusing on the pretty-printed tab is inconvenient and a bit frustrating.

**Comment by jasonLaster** [comment]
are these issues tracked elsewhere? if so can we add their iddue ids?

**Comment by juliandescottes** [comment]
Some other pretty print issues:

![debugger_pretty_print](https://user-images.githubusercontent.com/1141550/32519718-ef09491c-c40d-11e7-9209-b70f9493a74d.gif)

STRs: 
- pretty print script.js
- close the pretty print tab
- add a breakpoint in the first line of startAnimationTimer
- step over repeatedly

The pretty print tab comes back, despite being closed in step 2. The focus switches back and forth between the two tabs.

The script I use to get this behavior is 
```
(function () {
  let timer;
  let map = {};
  var startAnimationTimer = function(id) {
    var item = map[id];

    if (timer) {
      window.clearTimeout(timer);
    }

    timer = window.setTimeout(function() {
      startAnimationTimer(id++);
    }, 50);
  };

  startAnimationTimer(0);
})();
```

served in an empty html file.

(needs to be a bit complex in order to trigger the switch back and forth between the pretty printed and non pretty printed version)

**Comment by jasonLaster** [comment]
the gutter issue is fixed

**Comment by jasonLaster** [comment]
@juliandescottes added a new issue for your bug and linked above

**Comment by juliandescottes** [comment]
@jasonLaster sorry, where's the link?

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/issues/4714

**Comment by violasong** [comment]
Sometimes Pretty Print takes a while to work (e.g. 4 seconds) with no indication that anything's happening - seems like we need a progress indicator of some sort, like the bouncing ball animation from the Firefox loading tabs.
