### ISSUE TITLE
[Search] Quick Open follow up

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4488]
#### Next Steps
- [ ] jump to call stack frame
- [ ] jump to breakpoint
- [x] style matched fuzzy characters
- [x] show indicator if symbols are still being parsed

#### Styling
- [ ] style focused result item
- [ ] style modal border shadow
- [x] style line numbers (i think we should drop the colon)
- [ ] style the input bar (i think it's a bit small)

![](http://g.recordit.co/RLOuU9WjeQ.gif)

#### style matched fuzzy characters (@princiya)

I love how atom styles matched characters. It might be nice to experiment w/ [downshift][d] and see if it could help us. Otherwise, we could do something what [fuzzyaldrin][f] gives us. Or, do something custom like what [projectSearch][p] does

![Screen Shot 2017-10-25 at 10.03.17 AM.png](https://shipusercontent.com/0301ef58052672b38cbb518275aeeacc/Screen%20Shot%202017-10-25%20at%2010.03.17%20AM.png)

[d]:https://github.com/paypal/downshift
[p]:https://github.com/wldcordeiro/debugger.html/blob/master/src/components/ProjectSearch/textSearch/utils/highlight.js#L17
[f]:https://github.com/jeancroy/fuzz-aldrin-plus

**Comment by princiya** [comment]
@jasonLaster at this point, to what I understand, is this an issue to experiment with the below possibilities?
- downshift
- fuzzyaldrin
- projectSearch

**Comment by wldcordeiro** [comment]
@princiya We're using fuzz-aldrin-plus already. I don't think we have a serious need to bring in something like downshift as it's just another dependency when we've built a decent solution already. As for projectSearch? I'm not sure what you mean by that.

**Comment by jasonLaster** [comment]
yeah - lets build the simple thing first for styling the matched chars... making them blue :) or something like that. I think what we did for project search is pretty close... The basic algorithm for finding the chars for a query like "foo" is to take the match result string and split it up into matching and not-matching spans. so if the result is` "af/my/o/o.js",` => `"a", "f","/my/","o","/","o",".js"`

**Comment by princiya** [comment]
ok, that sounds good. so I shall focus on the styling part for now.

**Comment by jasonLaster** [comment]
yep

**Comment by wldcordeiro** [comment]
Looks like the action items from #4431 got moved but this comment from @violasong is useful for anyone following up on the shadow fix.

> Ah yes! The shadow should probably be black. We should also try these shadow specs from the design system: http://design.firefox.com/photon/patterns/shadows.html It's meant for light mode so the color/opacity is probably too subtle for dark mode. However I'd love to see the "Shadow 20" or "30" elevation here.

**Comment by wldcordeiro** [comment]
I noticed that since we do a little bit of deferring with symbol parsing we could gain from having an indicator. This may require more work across redux code as well to track this state but it'd be nice to be able to display a "parsing" message rather than "0 results" in function/variable search when that is the case.

**Comment by princiya** [comment]
Ok. So, I am on this styling task. Can you please assign this to me?

I am starting with this one: 
> style line numbers (i think we should drop the colon)

**Comment by jasonLaster** [comment]
@princiya did you get an invite to the team a couple weeks ago?

**Comment by princiya** [comment]
No i did not..

**Comment by princiya** [comment]
I have been trying to understand the file structure for the `search` component.

And, the `:` is coming from [here](https://github.com/devtools-html/debugger.html/blob/master/src/utils/quick-open.js#L74).

What is the best way to drop this in `ResultList`?
- Remove it from `utils/quick-open.js`?
  - There might be other dependencies involved here.
  - In other words, what is the motivation to add `:` in this file?
- Parse `subtitle` to display only the number without the `:` [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/ResultList.js#L45)?

**Comment by jasonLaster** [comment]
invited!

**Comment by atwalg2** [comment]
/claim @princiya I'm going to work on picking up where you left off
