### ISSUE TITLE
Test Coverage Push

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#5100]
This is a tracking issue for the test coverage push. The goal is to increase our test coverage 10-20% by targeting some lower hanging fruits. I had started this push around January 9th 2018 and the output of `yarn test --coverage` gave me ~*56%* as our total coverage. Let's see where we're at on February 9th!

## Stretch goal bump total coverage to ~*76%*

* [ ] `src/components/shared
  - [x] `Button/`
    - [x] Close
    - [x] CommandBarButton
    - [x] PaneToggle
  - [x] Accordion
  - [x] Badge
  - [x] BracketArrow
  - [x] Dropdown
  - [ ] ManagedTree
  - [x] Modal
  - [x] Popover
  - [x] PreviewFunction
  - [x] ResultList
  - [x] SearchInput
  - [ ] Svg
* [ ] `src/utils/editor/`
  - [ ] create-editor
  - [ ] getTokenLocation
  - [ ] index.js
  - [ ] source-documents.js
  - [ ] source-editor.js
  - [ ] source-search.js
...

**Comment by jasonLaster** [comment]
Here's the first PR https://github.com/devtools-html/debugger.html/pull/5097

It's a GREAT example for how to write jest unit tests!

**Comment by jasonLaster** [comment]
I'll work on `scr/utils/frame`

**Comment by wldcordeiro** [comment]
Working on `src/utils/editor/`

**Comment by wldcordeiro** [comment]
Updating the issue with adjusted goals as we had been measuring the coverage wrong and Jest was missing stuff. Lower percentage now. 🙁 Let's get this up there! 🎉

**Comment by mutdmour** [comment]
Covered SourcesTree. Will work on Outline next 😀

**Comment by adancarrasco** [comment]
Hi, I'm planning to help on this task, just wondering if the list is up-to-date? I was planning to contribute to `astBreakpointLocation test` but I'm seeing it in the code from yesterday's cloned repo. 😃

**Comment by adancarrasco** [comment]
I will work on `src/utils/ui`.

**Comment by mutdmour** [comment]
I will work on `source-documents`

**Comment by jasonLaster** [comment]
@kenjiO go for it!

**Comment by marcogallo566** [comment]
Can I work on `src/utils/fromJS`?

**Comment by jasonLaster** [comment]
@marcogallo566 we're using that file less and less, id recommend a different one

**Comment by marcogallo566** [comment]
Is `src/utils/pause/scopes/getScope` a good one?

**Comment by jasonLaster** [comment]
yep

**Comment by mutdmour** [comment]
sorry, could not setup the project before for some reason and don't have time to take on `source-documents` anymore. if someone else wants to take it on

**Comment by connorholyday** [comment]
I'm happy to take on `source-documents`

**Comment by huoxito** [comment]
hey all any chance someone could check the items already implemented pls?

I was going through the list and I see spec files for all items in _src/Components, src/components/PrimaryPanes_. The _src/utils/_ list seems to be missing only _result-list, source-maps, source-queue_.

I want to give a try on [result-list](https://github.com/devtools-html/debugger.html/blob/3a530479dd10ed05a0394e714153dcb30a8bce03/src/utils/result-list.js) would that still make sense? See https://github.com/devtools-html/debugger.html/pull/6805

**Comment by jasonLaster** [comment]
@huoxito result-list would be great.
