### ISSUE TITLE
[telemetry] Tracking issue for telemetry

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#5403]
- [x] Debugger Open
- [ ] Debugger Cold Open
- [ ] debugger open on debug statement
- [ ] Select Source (time)
- [ ] Reload page with Debugger open
- [ ] Close toolbox with Debugger open
- [ ] # of sources listed
- [ ] Select Source Count
- [ ] prettified count
- [ ] # of files opened (which had source maps)
- [ ] framework
- [ ] # of breakpoints added

Pausing:
- [ ] Stepping (time)
- [ ] Pausing (time)
- [ ] Preview Count
- [ ] Preview (time)
- [ ] Step Over Count
- [ ] # of pauses

Next Steps:
1. system to listen for actions

**Comment by codehag** [comment]
We should revisit this from a product perspective, because it is likely that we are not getting useful data from telemetry for performance. in this case we might be able to get rid of a few probes

**Comment by jasonLaster** [comment]
closing as this is out of date.
