### ISSUE TITLE
[Scopes] Tracking issue for known original scope mapping tasks

### ISSUE THREAD

**Issue by loganfsmyth** [devtools-html/debugger.html#5561]
Not necessarily all required, but a general tracking issue for known tasks around the original scope work

#### Bugs
* [x] Exclude Flowtype bindings from original scope binding lists
* [x] Generate proper scope bindings when bindings are referenced before they are declared
* [x] Imported bindings that have been optimized out may cause errors
* [x] Handle Webpack's eval-source-map `devtool` option (generated code for map runs inside `eval()`)
* [x] Some mappings include multiple locations, and often the simple binary search in `source-map` finds one that isn't ideal. We should expose `allGeneratedPositionsFor` so we can decide for ourselves. [PR](https://github.com/devtools-html/devtools-core/pull/1014)
* [x] Resolving generated locations can sometimes result in ranges larger than a single variable. Most commonly, this is if the identifier is the first thing on its own line, because generally the mapped range includes the indentation whitespace
  * [x] `this` is not mapped in perf.html's `TabBar#mouseDownListener` #5967
  * [x] `Preview/index.js`'s `addExpression` (and other destructured/shorthand-referenced bindings) show as `(unmapped)` #5967
* [x] Investigate performance of mapping logic
  * [x] Optimize the perf of generated binding search [PR](https://github.com/devtools-html/debugger.html/pull/5919)
  * [x] Optimize the perf of original binding mapping by batching the lookup into a single call
    * [x] Implement batching in the devtools-core worker https://github.com/devtools-html/devtools-core/pull/1029
    * [x] Use the batched logic to optimize the debugger generated range lookup #5967
* [x] Bindings sometimes show as `(unmapped)` instead of `(optimized out)` for module imports. #5984
* [x] dependencies are unmapped in debugger.html `actions/tabs.js:closeTab` #6040
  * If a mapping has multiple ranges, we should search for mappings in all of them
* [x] `JSXIdentifier` nodes are not included in visitor.js's binding results #6047
* [x] this is mapped to `_this` in a class property in this [app](https://dbg-class-prop-this.glitch.me/) #6072 
* [x] Expression variable remapping also renames variables that are shadowed by re-declaration in the expression #6087
* [x] Consider bailing out of mapping if a range has too many applicable bindings #6099
* [x] 'this' doesn't map fully in arrow functions #6163
* [x] Handle single-identifier mapped ranges with more broad matching to addresshttps://github.com/Microsoft/TypeScript/issues/22834
  * [x] Attempt #1, which was reverted partially [PR: #6092]
  * [x] Remove overly-broad matching to allow re-applying matching work #6202
* [x] Rename the various "babel-" files to something more generic, since we're also covering TS? #6229
* [ ] Ensure that regenerator maps `yield` statements to `return` statements [regenerator issue #342](https://github.com/facebook/regenerator/issues/342) [regenerator PR #344]( https://github.com/facebook/regenerator/pull/344)
* [ ] Handle function body scope with lex and nonlex decls #6387
* [ ] Turns out Babel's `t.isReferenced` (used in the parser worker's visitor.js) isn't great
  * `[ foo ] = []` does not recognize `foo` as a reference
  * `foo = 42` is not recognized either
  * `{ prop: foo } = {}` _is_ because it is an object property, even if it is inside a pattern
* [ ] Stepping to the end of a function
* [ ] Use the original file ranges to more effectively exclude whole-line mappings

#### Features 

* [x] Explore how watch expressions among other things can leverage the original scope data
* [x] Enable Typescript parsing via Babylon
* [x] Rewrite expressions in the browser console using original scope maps
  * [x] (1/3) [PR](https://github.com/devtools-html/debugger.html/pull/5822)
  * [x] (2/3) make the console use the panel helper to map
  * [x] (3/3) Add mochitests for mapped console behavior
* [ ] DECIDED-AGAINST: ~~Create sourcemaps for console rewritten expressions~~
* [ ] DECIDED-AGAINST: ~~Consider making the console autocomplete take original scopes into account~~
* [ ] Consider adding support for "sections" in sourcemaps
* [ ] Handle complex expression mappings better
  * [ ]  We should execute module namespace getters to show the real value. Modules generally use getters for live values, rather than side-effects, so it should be within user expectations to trigger those
  * [ ] Some module imports are mapped to function calls instead of property accesses, but we cannot currently call these functions to get their values

#### Documentation

* [x] Document the general architecture #6225

#### UI

* [x] Allow users to toggle between original and generated scopes inside the Scopes pane

#### Typescript / Angular

* [ ] ~~Declaration binding identifiers are not mapped consistently [Issue](https://github.com/Microsoft/TypeScript/issues/22833)~~ Handled in PR #6092, though it would still be good for TS to do better around decorators and exports
* [ ] UNNEEDED: ~~Single-identifier arrow arguments are not mapped to identifiers [Issue](https://github.com/Microsoft/TypeScript/issues/22834)~~

#### Vue

* [x] Off-by-one (at least) mappings when used with Babel: [Issue](https://github.com/babel/babel/issues/7632) [PR](https://github.com/babel/babel/pull/7761)
* [x] We'll need to enable the existing HTML parser to also run on original `.vue` files #6167
* [ ] Look into how imports and exports are handled, and ensure that they resolve original bindings properly

#### EmberJS

* [x] Ember requires developers to opt into Babel's source-maps, but even when they do they are often ignored: [PR](https://github.com/ben-ng/sourcemap-validator/pull/12)
* [x] Ember appears to a have custom import logic for its own core imports, rewriting them to reference the `Ember` global. These currently show as `(unmapped)` and we should see if that is fixable [PR](https://github.com/devtools-html/debugger.html/pull/5871)
* [x] Some mappings include multiple locations, and often the simple binary search in `source-map` finds one that isn't ideal. We should call `getAllGeneratedPositions` [PR](https://github.com/devtools-html/debugger.html/pull/5871)

#### Ecosystem

* [x] Backport `this`/`arguments`/`import`/`inputSourceMap` Babel 7 fixes to Babel 6 [Babel PR](https://github.com/babel/babel/pull/7812)
* [ ] Expand testcases for other bundling/sourcemap generation tooling
  * [ ] Webpack
  * [ ] Rollup
  * [ ] Parcel
  * [ ] Explore how we handle minified code
* [ ] Explore non-Babel implementations of imports to see if mappings need improvements
* [ ] Create more testcases around Babel's binding mappings for various complex transformations

**Comment by jasonLaster** [comment]
![original preview](https://user-images.githubusercontent.com/254562/37664954-99287814-2c32-11e8-9b0c-d8088148ec3c.gif)

**Comment by jasonLaster** [comment]
<img src='https://shipusercontent.com/df8b4e80b7270b3b7aa1e06348f8d1c3/features.png' title='features.png' width=724>


# this is not mapped in perf.html TabBar#mouseDownListener

STR:
1. clone https://github.com/devtools-html/perf.html/
2. yarn install, yarn start
3. go to [url](http://localhost:4242/public/fa1302b5668d67f1434932edd5fa60932d9895ac/markers/?hiddenThreads=&markerSearch=&range=2.1344_3.2600&react_perf&thread=5&threadOrder=0-2-3-4-5-1)
4. Add a breakpoint in `tabBar.js#mouseDownListener`
5. click a tab

**Comment by jasonLaster** [comment]
STR:
1. run debugger.html
2. navigate to localhost:8000
3. add a breakpoint in actions/tabs.js `closeTab`
4. right click on a tab in the launchpad and select close tab

![Screen Shot 2018-04-19 at 8.57.50 AM.png](https://shipusercontent.com/cc4b544c1d9ce8402ee898a6a2348cbc/Screen%20Shot%202018-04-19%20at%208.57.50%20AM.png)

**Comment by jasonLaster** [comment]
STR:
1. run debugger.html
2. navigate to localhost:8000
3. add a breakpoint in preview/index.js `onMouseOver`
4. pause the launchpad debugger, mouse over a variable!

[Screen Shot 2018-04-20 at 9.11.57 AM.png](https://shipusercontent.com/8e607ec2653499399b603b8bc82042e1/Screen%20Shot%202018-04-20%20at%209.11.57%20AM.png)

**Comment by jasonLaster** [comment]
STR:

1. go to https://dbg-class-prop-this.glitch.me/
2. add a breakpoint in app.jsx

<img src='https://shipusercontent.com/82e8d5d533df3363361dde9b0b5100c4/Screen%20Shot%202018-04-21%20at%208.58.56%20AM.png' title='Screen Shot 2018-04-21 at 8.58.56 AM.png' width=681>

**Comment by jasonLaster** [comment]
Found a new case with nightly today.

STR:
1. open http://localhost:8000/?react_perf&firefox-tab=child1/tab1
2. navigate to SecondaryPanes/Breakpoint.js
3. add a breakpoint on 41
4. add a breakpoint in the debuggee (todomvc)

the missed bindings are: getBreakpointLocation, getBreakpointText, this corresponds with the functions defined in the module scope


![Screen Shot 2018-05-10 at 3.51.07 PM.png](https://shipusercontent.com/c209fa3831d98bdfd988df0cf5a08b38/Screen%20Shot%202018-05-10%20at%203.51.07%20PM.png)

**Comment by jasonLaster** [comment]
@loganfsmyth and i looked into it and it looks like it is related to the fact that a function and class are inside of a function body scope

```js
(function() { /* outer anonymous (variable level) */
  /* lexical scope */
  "use strict";

  function getBreakpointText() {
    console.log(2)
  }

  class Breakpoint {
  }

})()
```

https://gist.github.com/af8e91b7c322d25b1fc122d7d65ffa6f

**Comment by loganfsmyth** [comment]
Closing in favor of #6400

**Comment by digitarald** [comment]
@loganfsmyth what are the minimum versions for libraries/tools (babel, ember, etc) that you fixed during this work? I want to make sure to document the work, which would help developers ensure the best debuggable output.

**Comment by loganfsmyth** [comment]
@digitarald `babel-core@^6.23.3` and `@babel/core@^7.0.0-beta.47` are the first versions of their major versions to include all the fixes we've implemented thus far. A few fixes landed earlier in 7.x, but `beta.47` includes the most recent fixes we make, which were for Vue.
