### ISSUE TITLE
[Breakpoints] New Breakpoint UI

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5773]
- [x] https://github.com/devtools-html/debugger.html/issues/5795
- [ ] https://github.com/devtools-html/debugger.html/issues/5903
- [x] https://github.com/devtools-html/debugger.html/issues/5908
- [x] https://github.com/devtools-html/debugger.html/issues/5796
- [x] https://github.com/devtools-html/debugger.html/pull/5823
- [x] https://github.com/devtools-html/debugger.html/issues/5849

@violasong has so generously provided this awesome new mockup for an improved breakpoint UI:

![breakpointsux](https://user-images.githubusercontent.com/46655/37845268-10dc99f0-2e98-11e8-8f90-b2296860e885.png)

This issue will be used as the official tracking issue for the new breakpoint UI work.  Additionally the breakpoints content should look like:

![items](https://user-images.githubusercontent.com/46655/37848655-e39f68ea-2ea2-11e8-84ce-e83f1d2bc0b5.png)

**Comment by violasong** [comment]
Here's how it would look without the icons. (I think their shape makes them clash a bit when next to checkboxes)
<img width="288" alt="image" src="https://user-images.githubusercontent.com/55994/37930732-70b0ab02-30f8-11e8-93ed-48e916eef0c7.png">

Alternatively I think making the main exceptions icon a little smaller and spaced closer to the text would work fine, and it would be a nice hint for Chrome users
![image](https://user-images.githubusercontent.com/55994/37930870-da08602c-30f8-11e8-8d4a-a08e13342aa0.png)
