### ISSUE TITLE
Quality Sprint

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6399]
#### Toolbox

- [x] the debugger tab flashes when you add a breakpoint #6382 
- [x] Following link to large file from Console doesn't react for a while #4654
- [ ] [Console] Clicking frame from console does not highlight line  #4100   

#### Editor

- [x] does not go to the correct location (when loading) #6353   
- [x]  Weird style when hovering gutter line with horizontally scrolled editor #6451 
- [x] Jumping to function definitions should go to right location #6028  🏃
- [x] "Reveal in Tree" Editor Context Menu Item Switches from PrettyPrinted Tab to Original Tab #5564
- [x] Adding a breakpoint should not cause the editor to scroll #4852  
- [x] Highlight Line updates too frequently #6543 #6588
- [x] Syntax highlighting flashes when stepping 
- [x] angular's icon does not show up in tabs #6543

#### Preview 

- [x] 'Split console' overlays the debugger variable tooltip #5134
- [x] Preview should use new token events #6193 

#### Source Tree 

- [x] Show original files when the files have the same URL  #5663 #5902 🏃
- [x] reveal in tree doesn’t work with directory roots #6027 
- [x] Missing path segment for resource:// and extension:// URLs #5759 
- [x] (index) click weirdness #5918
- [x] Clean up `source.get ? source.get('url') : source.url` Usage #6441 

#### Breakpoints

- [x] Polish UX for removing column breakpoints #5833  
- [x] breakpoint does not appear on reload #6355 
- [x] improve breakpoint syncing cases #5570 🥇  🏃
- [ ] we should resume if we pause at an old breakpoint #4104
- [ ] Breakpoint changes its place on page refresh #6580   🏃

#### UI Polish

- [x] [Tabs] Title Not Matching Tree Title #6394 

--- 

🥇 P1
🥈 P2
🏃 In Progress

**Comment by jasonLaster** [comment]
closing as we're focusing on 64 quality now
https://github.com/devtools-html/debugger.html/issues/6777
