### ISSUE TITLE
Quality Sprint (64)

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6777]
This is a follow up issue for #6399

### Performance

- [x]  Storing too much data into devtools.debugger.tabs pref #6546 🏃 
- [x]  Delay when opening debugger on reddit #6828
- [x]  Debugger in background causes hangs #4896

### Breakpoints / Stepping 

- [x]  [Preview] preview can initially lag #6868 🏃 
- [x]  [Preview] immutable records in a react component are not shown #6694

### SourceMaps

- [x] Upgrade to the newest sourcemap version #5598 

### UI

- [x] [Scopes] Save variable expand state while stepping #3269 
- [x] Framework icons only load on file openings and cause visual jitter #6753
- [x] Active file in source pane is sometimes not selected  #6750

**Comment by jasonLaster** [comment]
🍷
