### ISSUE TITLE
Quality Sprint (65)

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#7099]
This is a follow up issue for #6399

### Performance

- [x]  Storing too much data into devtools.debugger.tabs pref #6546 🏃 
- [x]  Full Project Search is really slow #6094
- [ ]  [Stepping]"step-over" (F10) takes a lot of time #6313
- [x]  Delay when opening debugger on reddit #6828
- [x]  Debugger in background causes hangs #4896
- [ ]  CPU churn when switching back to tab with debugger open #6010

### Breakpoints / Stepping 

- [x]  [Preview] preview can initially lag #6868 🏃 
- [x]  [Preview] immutable records in a react component are not shown #6694
- [x]  Setting breakpoint in JSX adds another breakpoint on the line above #6685
- [x]  [Breakpoints] Breakpoint changes its place on page refresh #6580 🏃 
- [ ]  [Breakpoints] we should resume if we pause at an old breakpoint #4104
- [x]  [Breakpoints] U+2028 and U+2029 characters throw off pause locations  #5782
- [ ] [Breakpoints] Break at wrong location #6873
- [ ] Stepping can take you from original to generated code when next step has no original mapping #6949

### SourceMaps

- [x] Upgrade to the newest sourcemap version #5598 
- [x] Use built-in URL https://github.com/mozilla/source-map/issues/275
- [x] [SourceMaps] Wrong warning location #6923
- [x] [Prettyprint] fails with sourceMap error when Source Maps is off #6328

### UI

- [x] [Scopes] Save variable expand state while stepping #3269 
- [x] Framework icons only load on file openings and cause visual jitter #6753
- [x] Active file in source pane is sometimes not selected  #6750
- [ ] Two Breakpoints Active in Secondary Pane #6734 🏃 
- [ ] Navigating callstack conflicts with search result focusing  #6747 
- [x] Framework collapsing also collapses user-land component  #6792 
- [x] [Tabs] Sources without URLs should have a tab #5102

**Comment by digitarald** [comment]
@jasonLaster @janodvarko could we carry over https://github.com/devtools-html/debugger.html/issues/4100 this this meta. It was in the 64 sprint and got checked off without being fixed.

**Comment by jasonLaster** [comment]
Closing as we're starting #7677
