### ISSUE TITLE
Watch Expressions 

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#916]
Tracking ticket for watch expression

Tasks:
- [x] Polish UI #1599 
  - [x] Prevent duplicate expressions 
  - [x] Fix editing expressions 
  - [x] Re-evaluate on resume
  - [x] cursor on input should be "text"
  - [x] close button is off
  - [x] expressions should not expand by default
  - [x] re-evaluate when a frame is selected
  - [x] can't remove last expression
- [x] UI wonkiness #1610 
- [x] editing / adding wonkiness #1609
- [x] add watch expressions pane in vertical mode #1649
- [x] Refactoring #1650
   - [x] Extract expressions actions and reducer
  - [x] remove expression id (because they're unique!)
- [x] add selection to watch expressions
- [x] Final expression doesn't remove #1594 
- [x] clean up list view #1522
- [x] cleanup close button #1523
- [x] Adjust header buttons height so that the header is normal height #1524 
- [x] Clean up input UI #1491
- [x] improve the preview https://github.com/devtools-html/debugger.html/issues/1350
- [x] evaluate expression when not paused #1525 
- [x] edit expression when paused #1526 
- [x] review refreshing an expression #1521
- [x] cleanup the header buttons https://github.com/devtools-html/debugger.html/issues/1347
- [x] Header button to show expression input
- [x] Header button to refresh (re-evaluate) watched expressions
- [x] Adjust colors to match other panels in the accordion
- [x] display `<not available>` when value is undefined
- [x] refresh button on frame.
- [x] Add watch expressions by context menu in editor #1596
- [x] Bug - Watch expressions don't evaluated on Chrome (suggestions?)  (yup, ignore it)

**Comment by jasonLaster** [comment]
@jbhoosreddy two things:
- i've noticed that the values might not be computing on the pause action.
- the global value is currently the URL of the page, but that is changing here #884, which i think will be a nice stylistic improvement.
