### ISSUE TITLE
Polish Dark Theme

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#988]
I just did a quick walk through of the dark theme and found a couple of UI color issues. I'm not sure how we want to fix this as there's a one-to-one mapping between light and dark values...

**Issues:**
1. [x] right sidebar command buttons colors are off (step in, step over especially) - #995
2. [x] breakpoints - grey breakpoint line, grey remove button. - #1010
3. [x] call stack - grey file name - #1011
4. [x] accordion header - white background when hovering - #999 
5. [x] tabs - the border, non active tabs... - #994 
6. [x] autocomplete - generally off, but it's being worked on now.
7. [x] debug line - the green looks off here both on the debug line and in the active breakpoint border. - #1012
8. [x] source footer - the pretty print icon color is off - #997
9. [x] dropdown - the background is set to white and should be theme aware, contents too - #1008 

![](http://g.recordit.co/dINAG182bU.gif)

**How do you change themes locally?** You can edit the theme locally [here](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)

**How do we fix these?** Add CSS overrides in the different components. Here's an example of how we could fix the right sidebar commands.

``` diff
diff --git a/public/js/components/RightSidebar.css b/public/js/components/RightSidebar.css
index 5f5f8b4..794aa0d 100644
--- a/public/js/components/RightSidebar.css
+++ b/public/js/components/RightSidebar.css
@@ -40,6 +40,10 @@ html[dir="rtl"] .command-bar {
   transition: opacity 200ms;
 }

+:root.theme-dark .command-bar > span {
+  stroke: var(--theme-body-color);
+}
+
 html:not([dir="rtl"]) .command-bar > span {
   margin-right: 0.7em;
 }
```

**How do I choose the right color?** Hmm, it's up to you. We have a list of variables [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/public/js/lib/themes/variables.css). What I do is look for similar colors in the app and then see what variable it uses in the inspector.

**Comment by wldcordeiro** [comment]
The color values here aren't up to date but I was told this is a good resource to look through for theme colors https://developer.mozilla.org/en-US/docs/Tools/DevToolsColors

**Comment by jasonLaster** [comment]
Hey @monicau any interest in a second OSS issue :)

**Comment by monicau** [comment]
Hey, sure, count me in!  I see that this is made up of multiple other issues. Do I create a new branch for each of the issues and do separate pull requests?

**Comment by wldcordeiro** [comment]
@monicau take one of the issues from the list, make a branch for it and a PR for it. This is a tracking issue for all the smaller ones. 😄

**Comment by jasonLaster** [comment]
Great! Up to you. One PR for many issues is fine.

**Comment by helenvholmes** [comment]
Going to close this issue out—looks like all the current dark theme issues either have PRs open for them or have been resolved.
